---
title: "Final Project"
author: "Kristin Bryan, Olivia Litke, Mary McDonnell"
date: "12/13/2020"
output: 
  html_document:
    keep_md: TRUE
    toc: TRUE
    toc_float: TRUE
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data}
bad_drivers <- read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/bad-drivers/bad-drivers.csv")

covid19 <- read.csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")

mask_data <- read.csv("https://raw.githubusercontent.com/kristinbryan/covid-19-data/master/mask-use/mask-use-by-county.csv")

census_pop_est_2018 <- read_csv("https://www.dropbox.com/s/6txwv3b4ng7pepe/us_census_2018_state_pop_est.csv?dl=1") %>% 
  separate(state, into = c("dot","state"), extra = "merge") %>% 
  select(-dot) %>% 
  mutate(state = str_to_lower(state))
```

```{r}
library(tidyverse)
library(lubridate)
library(openintro)
library(maps)
library(ggmap)
library(gplots)
library(RColorBrewer)
library(sf)
library(ggthemes)
```

# Welcome to our final!
We chose to use data from fivethirtyeight.com to tell a story about the world we live in and make somefhdsafhdjsaklfa

#
```{r}
mask_data %>% 
  mutate(x = ifelse(COUNTYFP <= 1133, "alabama", 
                    ifelse(COUNTYFP <= 2290, "alaska",
                           ifelse(COUNTYFP <= 4027, "arizona", 
                                  ifelse(COUNTYFP <= 5149, "arkansas",
                                         ifelse(COUNTYFP <= 6115, "california",
                                                ifelse(COUNTYFP <= 8125, "colorado",
                                                       ifelse(COUNTYFP <= 9015, "connecticut",
                                                              ifelse(COUNTYFP <= 10005, "delaware",
                                                                     ifelse(COUNTYFP <= 11001, "district of columbia",
                                                                            ifelse(COUNTYFP <= 12133, "florida",
                                                                                   ifelse(COUNTYFP <= 13321, "georgia",
                                                                                          ifelse(COUNTYFP <= 15009, "hawaii",
                                                                                                 ifelse(COUNTYFP <= 16087, "idaho",
                                                                                                        ifelse(COUNTYFP <= 17203, "illinois",
                                                                                                               ifelse(COUNTYFP <= 18183, "indiana",
                                                                                                                      ifelse(COUNTYFP <= 19197, "iowa",
                                                                                                                             ifelse(COUNTYFP <= 20209, "kansas",
                                                                                                                                    ifelse(COUNTYFP < 21000, "kentucky",
                                                                                                                                           ifelse(COUNTYFP < 22000, "louisiana",
                                                                                                                                                  ifelse(COUNTYFP < 23000, "maine",
                                                                                                                                                         ifelse(COUNTYFP < 24000, "maryland",
                                                                                                                                                                ifelse(COUNTYFP < 25000, "massachusetts",
                                                                                                                                                                       ifelse(COUNTYFP < 26000, "michigan",
                                                                                                                                                                              ifelse(COUNTYFP < 27000, "minnesota",
                                                                                                                                                                                     ifelse(COUNTYFP < 28000, "mississippi",
                                                                                                                                                                                            ifelse(COUNTYFP < 29000, "missouri",
                                                                                                                                                                                                   ifelse(COUNTYFP < 30000, "montana",
                                                                                                                                                                                                          ifelse(COUNTYFP < 31000, "nebraska",
                                                                                                                                                                                                                 ifelse(COUNTYFP < 32000, "nevada",
                                                                                                                                                                                                                        ifelse(COUNTYFP < 33000, "new hampshire",
                                                                                                                                                                                                                               ifelse(COUNTYFP < 34000, "new jersey",
                                                                                                                                                                                                                                      ifelse(COUNTYFP < 35000, "new mexico",
                                                                                                                                                                                                                                             ifelse(COUNTYFP < 36000, "new york",
                                                                                                                                                                                                                                                    ifelse(COUNTYFP < 37000, "north carolina",
                                                                                                                                                                                                                                                           ifelse(COUNTYFP < 38000, "north dakota",
                                                                                                                                                                                                                                                                  ifelse(COUNTYFP < 39000, "ohio",
                                                                                                                                                                                                                                                                         ifelse(COUNTYFP < 40000, "oklahoma",
                                                                                                                                                                                                                                                                                ifelse(COUNTYFP < 41000, "oregon",
                                                                                                                                                                                                                                                                                       ifelse(COUNTYFP < 42000, "pennsylvania",
                                                                                                                                                                                                                                                                                              ifelse(COUNTYFP < 44000, "rhode island",
                                                                                                                                                                                                                                                                                                     ifelse(COUNTYFP < 45000, "south carolina",
                                                                                                                                                                                                                                                                                                            ifelse(COUNTYFP < 46000, "south dakota",
                                                                                                                                                                                                                                                                                                                   ifelse(COUNTYFP < 47000, "tennessee",
                                                                                                                                                                                                                                                                                                                          ifelse(COUNTYFP < 48000, "texas",
                                                                                                                                                                                                                                                                                                                                 ifelse(COUNTYFP < 49000, "utah",
                                                                                                                                                                                                                                                                                                                                        ifelse(COUNTYFP < 50000, "vermont",
                                                                                                                                                                                                                                                                                                                                               ifelse(COUNTYFP < 51000, "virginia",
                                                                                                                                                                                                                                                                                                                                                      ifelse(COUNTYFP < 53000, "washington",
                                                                                                                                                                                                                                                                                                                                                             ifelse(COUNTYFP < 54000, "west virginia",
                                                                                                                                                                                                                                                                                                                                                                    ifelse(COUNTYFP < 55000, "wisconsin",
                                                                                                                                                                                                                                                                                                                                                                           ifelse(COUNTYFP < 56000, "wyoming", ""))))))))))))))))))))))))))))))))))))))))))))))))))))
  
```

```{r}
mask_data %>% 
  mutate(alabama = COUNTYFP <= 1133,
         alaska = COUNTYFP <= 2290,
         arizona = COUNTYFP <= 4027,
         arkansas = COUNTYFP <= 5149,
         california = COUNTYFP <= 6115,
         colorado = COUNTYFP <= 8125,
         conneticut = COUNTYFP <= 9015,
         delaware = COUNTYFP <= 10005,
         district_of_columbia = COUNTYFP <= 11001,
         florida = COUNTYFP <= 12133,
         georgia = COUNTYFP <= 13321,
         hawaii = COUNTYFP <= 15009,
         idaho = COUNTYFP <= 16087,
         illinois = COUNTYFP <= 17203,
         indiana = COUNTYFP <= 18183,
         iowa = COUNTYFP <= 19197,
         kansas = COUNTYFP <= 20209,
         kentucky = COUNTYFP < 21000,
         louisiana = COUNTYFP < 22000,
         maine = COUNTYFP < 23000,
         maryland = COUNTYFP < 24000,
         massachusetts = COUNTYFP < 25000,
         michigan = COUNTYFP < 26000,
         minnesota = COUNTYFP < 27000,
         mississippi = COUNTYFP < 28000,
         missouri = COUNTYFP < 29000,
         montana = COUNTYFP < 30000,
         nebraska = COUNTYFP < 31000,
         nevada = COUNTYFP < 32000,
         new_hampshire = COUNTYFP < 33000,
         new_jersey = COUNTYFP < 34000,
         new_mexico = COUNTYFP < 35000,
         new_york = COUNTYFP < 36000,
         north_carolina = COUNTYFP < 37000,
         north_dakota = COUNTYFP < 38000,
         ohio = COUNTYFP < 39000,
         oklahoma = COUNTYFP < 40000,
         oregon = COUNTYFP < 41000,
         pennslyvania = COUNTYFP < 42000,
         rhode_island = COUNTYFP < 44000,
         south_carolina = COUNTYFP < 45000,
         south_dakota = COUNTYFP < 46000,
         tennessee = COUNTYFP < 47000,
         texas = COUNTYFP < 48000,
         utah = COUNTYFP < 49000,
         vermont = COUNTYFP < 50000,
         virginia = COUNTYFP < 51000,
         washington = COUNTYFP < 53000,
         west_virginia = COUNTYFP < 54000,
         wisconsin = COUNTYFP < 55000,
         wyoming = COUNTYFP < 56000,)
```




```{r}
#combine the data here 
```


```{r}
#covid map

car_covid_data %>% 
  group_by(state) %>% 
  mutate(case_rate = cases/est_pop_2018) %>% 
  ggplot(aes(fill = case_rate)) + 
  geom_map(aes(map_id = state),
           map = states_map) + 
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map()

```

```{r}
mask_data %>% 
  group_by(#need to make a state variable) %>% 
    mutate(mask_rate = ALWAYS / est_pop_2018) %>% 
      ggplot(aes(fill = mask_rate)) + 
      geom_map(aes(map_id = states), 
               map = states_map) + 
      expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map()
```


```{r}
#where will you die of what
covid_data %>% 
  group_by(state) %>% 
  mutate(case_rate = cases/est_pop_2018) %>% 
  
  # we need to 
  ggplot(aes(fill = death_rate)) + 
  geom_map(aes(map_id = state),
           map = states_map) + 
  expand_limits(x = states_map$long, y = states_map$lat) + 
  theme_map()
```


